"""Report API schemas."""

from datetime import date as dt_date

from pydantic import BaseModel, Field


class ReportItem(BaseModel):
    label: str = Field(..., description="Statistic label")
    value: int = Field(..., description="Statistic value")


class ReportResponse(BaseModel):
    period: str = Field(..., description="Report period")
    total_alerts: int = Field(..., description="Total alert count")
    by_severity: list[ReportItem] = Field(..., description="Alerts grouped by severity")
    top_exceptions: list[ReportItem] = Field(..., description="Most frequent exception types")


class DailyTrendPoint(BaseModel):
    hour: str = Field(..., description="Hour bucket, such as 09:00")
    count: int = Field(..., description="Alert count in the hour")


class DailyReportResponse(ReportResponse):
    date: str = Field(..., description="Report date in YYYY-MM-DD")
    risk_level: str = Field(..., description="Generated daily risk level")
    summary: str = Field(..., description="Generated daily summary")
    key_findings: list[str] = Field(..., description="Generated key findings")
    recommendations: list[str] = Field(..., description="Generated response recommendations")
    hourly_trend: list[DailyTrendPoint] = Field(..., description="Hourly alert trend")
    ai_provider: str | None = Field(default=None, description="AI provider used for generation")
    ai_model: str | None = Field(default=None, description="AI model used for generation")
    ai_generated: bool = Field(default=False, description="Whether text fields were generated by an external AI model")


class DeepSeekDailyReportRequest(BaseModel):
    date: dt_date | None = Field(default=None, description="Report date in YYYY-MM-DD")
    api_key: str = Field(..., min_length=1, description="User-provided DeepSeek API key")
    model: str = Field(default="deepseek-v4-flash", description="DeepSeek model name")
